{% set version = "0.4.1" %}

package:
  name: pylbm
  version: {{ version }}

source:
  git_url: https://github.com/pylbm/pylbm.git
  git_rev: {{ version }}

build:
  number: 0

requirements:
  build:
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - numpy
    - matplotlib
    - sympy >=1.1.1,<1.2
    - cython
    - h5py
    - mpich # [linux]
    - mpi4py
    - colorlog
    - colorama
    - cerberus
    - jinja2

test:
  imports:
    - pylbm

about:
  home: http://pylbm.readthedocs.io
  license: BSD 3-Clause
  summary: Package for numerical simulations using Lattice Boltzmann solvers

extra:
  recipe-maintainers:
    - gouarin
