{% set version = "0.3.1" %}

package:
  name: pylbm
  version: {{ version }}

source:
  url: https://github.com/pylbm/pylbm/archive/{{ version }}.tar.gz
  sha256: a47b911e5b12169a301987e0ae724c09969a6b50a302cdf53b921ca3bc707f03

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib
    - six
    - sympy >=1.1.1,<1.2
    - cython
    - h5py
    - mpi4py
    - future
    - colorlog

test:
  imports:
    - pylbm

about:
  home: http://pylbm.readthedocs.io
  license: BSD 3-Clause
  summary: Package for numerical simulations using Lattice Boltzmann solvers

extra:
  recipe-maintainers:
    - gouarin
