language: generic
os: osx
osx_image: xcode6.4

env:
  matrix:

    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    - secure: nA/nNsnnXsc0QYHNjLL9jAUN5BmKNusD7laof/zj/IxKNbtYqU+XxkLnOv4OqKXVpdU3JKSoMaMqXW9g3eBS0vx2olrn//mTW0A7xOL68Ta54weCTRu8pT4kvEo8wsht8IH4tH/3jstwfsqrLBWflARDroH2LLuk7IO+bgMt+CGsJ6r6kr58tBWeHp+pfrbYMseUIzvLpAm3vc2BPditNkQBEaOHtnY5F4W8gdkvcOl0fcJDJvOQmekhcOirBTrmflHTmjR5jf3gvxkuYpRN4GTo/sge+xRcDKFhceWKrmxpeF4ZkdHxj4hzmjXU0NLyN9Xx1yc1pYbvQklGSz0AWWMQDop13TEOQojrIqyqkW+wIm+CNvIIoEdPT8oLRQZNPbnRjCSrUOFJ+t8wH//LFk0yF/2s+mEdRTzTtP2XWXLRwzb8mIhU7xQ3mLStRU6V0WS32vbbASERSPlQRWAaJSARkNLNCakcNkPyNP6h3ptDCikpvh9DG59nSHV4Qfefj9qaulLNIr50nUEv1e/3pomX6J+u44AUVKMPs3h5eDptkUAgxkyJfkLQE79fAI4fU+T9D6X4GC2oB8X0a7uOeNiInkN55Pl5EwK5GJzYELa/kIKl+3R/TM7/LbW4yWOGHXp5npDZB37/gQWOKASjHvG4noHIFHYbquoX/ftIido=

before_install:
  - |
    (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
      python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
  - |
    echo ""
    echo "Removing homebrew from Travis CI to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew
install:
  - |
    echo ""
    echo "Installing a fresh version of Miniconda."
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b
  - |
    echo ""
    echo "Configuring conda."
    source /Users/travis/miniconda3/bin/activate root
    conda config --remove channels defaults
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --set show_channel_urls true
    conda install --yes --quiet conda-forge-build-setup
    source run_conda_forge_build_setup
script:
  - conda build ./recipe
  - upload_or_check_non_existence ./recipe pylbm --channel=main
